config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources  :recipes
  root 'recipes#index'

end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingradient.rb
class Ingradient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user	
	has_many :ingradients
	has_many :directions

	accepts_nested_attributes_for :ingradients,
	reject_if: proc { |attributes| attributes['name'].blank? },
  	allow_destroy: true
 	
 	accepts_nested_attributes_for :directions,
  	reject_if: proc { |attributes| attributes['step'].blank? },
  	allow_destroy: true

  	validates :title, :description, :image, presence: true

	has_attached_file :image
  
  	validates_attachment :image, styles: { medium: "300x300#" },
      content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] },
      size: { :in => 0..30.kilobytes } 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :recipes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
before_action :authenticate_user!, except: [:index,:show]
before_action :find_recipe, only: [:edit, :update, :show, :destroy]

def index
	@recipe = Recipe.all.order("created_at DESC")
end

def new
	@recipe = current_user.recipes.build
end

def create
	@recipe = current_user.recipes.build(recipe_params)	
	if @recipe.save
		redirect_to @recipe, notice: "Recipe Successfully Created !"
	else
		render 'new'
	end
end

def show
	
end

def edit
	
end

def update
	if @recipe.update(recipe_params)
		redirect_to @recipe
	else
		render 'edit'
	end
end

def destroy
	@recipe.destroy
	redirect_to root_path, notice: "Successfully deleted recipe"
end

private
	
	def find_recipe
		@recipe = Recipe.find(params[:id])
	end

	def recipe_params
		params.require(:recipe).permit(:title, :description, :image,
		ingradients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="nav navbar navbar-default">
		<div class="container">
			<div class="navbar-brand">
			<%= link_to "Recipe Box", root_path %>
			</div>
			<% if user_signed_in? %>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "New Recipe", new_recipe_path %></li>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				</ul>
			<% else %>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Sign Up", new_user_registration_path %></li>
					<li><%= link_to "Sign In", new_user_session_path %></li>
				</ul>
			<% end %>
			
		</div>
	</div>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: "alert" %>
		<% end %>
		<%= yield %>
	</div>	
</body>
</html>

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
	<div class="nested-fields">
		<%= f.input :step, input_html: { class: 'form-input form-control' } %>
		<%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
	</div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: {multipart: true} do |f| %>
	<% if @recipe.errors.any? %>
	<div id="errors">
		<p><%= @recipe.errors.count %></p>
		Prevented this recipe froms saving
		<ul>
			<% @recipe.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="panel-body">
		<%= f.input :title, input_html: {class: 'form-control'} %>
		<%= f.input :description, input_html: { class: 'form-control'} %>
		<%= f.input :image, input_html: { class: 'form-control'} %>
		
		<div class="row">
			<div class="col-md-6">
				<h3>Ingredients</h3>
				<div id="ingredients">
					<%= f.simple_fields_for :ingradients do |ingredient| %>
						<%= render 'ingradient_fields', f: ingredient %>
					<% end %>
					<div class="links">
						<%= link_to_add_association 'Add Ingredient', f, :ingradients, class: "btn btn-default add-button" %>
					</div>
				</div>
			</div>
			<div class="col-md-6">
				<h3> Directions </h3>
				<div id="directions">
					<%= f.simple_fields_for :directions do |direction| %>
						<%= render 'direction_fields', f: direction %>
					<% end %>
					<div class="links">
						<%= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button" %>
					</div>
				</div>
			</div>
		</div>
	</div>

	<%= f.button :submit, class: "btn btn-default" %>
<% end %>

app/views/recipes/_ingradient_fields.html.erb
<div class="form-inline clearfix">
	<div class="nested-fields">
		<%= f.input :name, input_html: { class: 'form-input form-control' } %>
		<%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
	</div>
</div>

app/views/recipes/edit.html.erb
<h1> Edit Recipe</h1>

<%=  render 'form' %>

app/views/recipes/index.html.erb
<% @recipe.each_slice(3) do |recipes| %>
	<div class="row">
		<% recipes.each do |recipe| %>
		<div class="col-md-4">
			<div class="recipe">
				<div class="image_wrapper">
					<%= link_to recipe do %>
						<%= image_tag recipe.image.url %>
						<h2><%= link_to recipe.title, recipe %></h2>
					<% end %>
				</div>
			</div>
		</div>
		<% end %>
	</div>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<br>

<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/recipes/show.html.erb
<div class="main_content">
	<div id="recipe_top" class="row">
		<div class="col-md-4">
 			<%= image_tag @recipe.image.url, class: "recipe_image" %>
		</div>			
		<div class="col-md-8">
			<div id="recipe_info">
				<h1> <%= @recipe.title %></h1>
				<p class="description"> 
					<%= @recipe.description %>
				</p>
				<p>
					Submitted By
					<%= @recipe.user.email %>
				</p>
			</div>
		</div>			
	</div>
	<div class="row">
		<div class="col-md-6">
			<div id="ingredients">
				<h2> Ingredients </h2>
				<ul>
					<% @recipe.ingradients.each do |ingredient| %>
						<li> <%= ingredient.name %> </li>
					<% end %>
				</ul>
			</div>
		</div>
		<div class="col-md-6">
			<div id="directions">
				<h2> Directions </h2>
				<ul>
					<% @recipe.directions.each do |direction| %>
						<li> <%= direction.step %> </li>
					<% end %>					
				</ul>
			</div>
		</div>			
	</div>
	<div class="row">
		<div class="col-md-12">		
			<%= link_to "Back", root_path, class: "btn btn-default" %>		
			<% if user_signed_in? %>
			<%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
			<%= link_to "Delete", recipe_path, method: :delete, data:{confirm: "Are you confirm ? "}, class: "btn btn-default" %>						
			<% end %>
		</div>
	</div>
</div>							